jobs:
- job: BuildWindowsWithSonarCloud
  displayName: Build for Windows\MSBuild With SonarCloud
  pool: Default
    
  variables:
    BUILD_WRAPPER_DOWNLOAD_URL: https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Prueba5'
      organization: 'bpbreinerpacheco0621'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'bpbreinerpacheco0621_Prueba5'
      cliProjectName: 'Prueba5'
      cliSources: '.'
      extraProperties: |
        sonar.cfamily.vscoveragexml.reportsPath=C:\Users\breinerpacheco\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9/CoverageResults/*/*.xml
  
  # Execute the tests to generate the coverage statistics
  - task: VSTest@2
    inputs:
      testSelector: 'testassemblies'
      testAssemblyVer2: |
        test1\*\test1.dll
        test2\*\test2.dll
      searchFolder: 'C:\Users\breinerpacheco\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9'
      resultsFolder: 'C:\Users\breinerpacheco\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9/CoverageResults'
      otherConsoleOptions: '/collect:"Code Coverage;Format=Xml"' # Necessary to have an XML coverage report
      codeCoverageEnabled: true
      testRunTitle: 'Run tests'
  - task: SonarCloudAnalyze@1
