jobs:
- job: BuildWindowsWithSonarCloud
  displayName: Build for Windows\MSBuild With SonarCloud
  pool: Default
    
  variables:
    BUILD_WRAPPER_DOWNLOAD_URL: https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Prueba5'
      organization: 'bpbreinerpacheco0621_Prueba5'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: |
        sonar.cfamily.vscoveragexml.reportsPath=$(System.DefaultWorkingDirectory)/CoverageResults/*/*.xml
  
  # Execute the tests to generate the coverage statistics
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        test1\*\test1.dll
        test2\*\test2.dll
      searchFolder: '$(System.DefaultWorkingDirectory)'
      resultsFolder: '$(System.DefaultWorkingDirectory)/CoverageResults'
      otherConsoleOptions: '/collect:"Code Coverage;Format=Xml"' # Necessary to have an XML coverage report
      codeCoverageEnabled: true
      testRunTitle: 'Run tests'
  - task: SonarCloudAnalyze@1
