jobs:
  - job: BuildWindowsWithSonarCloud
    displayName: Build for Windows\MSBuild With SonarCloud
    pool: Default
      
    variables:
      BUILD_WRAPPER_DOWNLOAD_URL: https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
    steps:
      - task: SonarCloudPrepare@1  
        inputs:
          SonarCloud: "Objetive"
          organization: "bpbreinerpacheco0621_Objetive-c"
          scannerMode: "CLI"
          configMode: "file"

      
      - task: SonarCloudAnalyze@1